# Generated by Django 4.1.5 on 2023-01-19 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wattmeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("unkey", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("value", models.PositiveIntegerField()),
                (
                    "wattmeter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.wattmeter"
                    ),
                ),
            ],
        ),
    ]
